### ISSUE TITLE
time issue !

### ISSUE THREAD

**Issue by smarta1980** [ElToberino/Tobers_Timeswitch#3]
Hello, Sir
I tried your project Tobers Timeswitch for ESP8266 then there is an issue let me explain it to you
if current time now is 8:30 AM then if set on time from 8:00 AM to 1:00 PM and do save times so why relay pin not turn on?

**Comment by ElToberino** [comment]
Hello,
this is not an issue, it's just like the program works. 
Regarding [the code](https://github.com/ElToberino/Tobers_Timeswitch/blob/21f9c8fb4790b772a113b8204edfcfe64225cf0e/timeswitch_1.0.ino#L595) (at line 595 following) you will see that the relay pin is triggered by a simple comparison of the current time and the switching times saved.
This means saving a time that has already passed by _can_ not trigger the relay pin. But that doesn't mind - because you can manually switch on/off you relay.
In your example just save the time and activate the relay manually by pressing the button at the same website. Of course the relay will be switched off automatically at 1:00 PM.
